const fakerTypes = 
    {
        address:[
            {title: 'Building Number', value: 'buildingNumber'},
            {title: 'Cardinal Direction', value: 'cardinalDirection'},
            {title: 'City', value: 'city'},
            {title: 'City Name', value: 'cityName'},
            {title: 'City Prefix', value: 'cityPrefix'},
            {title: 'City Suffix', value: 'citySuffix'},
            {title: 'Country', value: 'country'},
            {title: 'Country Code', value: 'countryCode'},
            {title: 'County', value: 'county'},
            {title: 'Direction', value: 'direction'},
            {title: 'Full Address', value: 'fullAddress'},
            {title: 'Latitude', value: 'latitude'},
            {title: 'Longitude', value: 'longitude'},
            {title: 'Nearby GPSCoordinate', value: 'nearbyGPSCoordinate'},
            {title: 'Ordinal Direction', value: 'ordinalDirection'},
            {title: 'Secondary Address', value: 'secondaryAddress'},
            {title: 'State', value: 'state'},
            {title: 'State Abbr', value: 'stateAbbr'},
            {title: 'Street Address', value: 'streetAddress'},
            {title: 'Street Name', value: 'streetName'},
            {title: 'Street Prefix', value: 'streetPrefix'},
            {title: 'Street Suffix', value: 'streetSuffix'},
            {title: 'Time Zone', value: 'timeZone'},
            {title: 'Zip Code', value: 'zipCode'},
            {title: 'Zip Code By State', value: 'zipCodeByState'},
        ],
        animal:[
            {title: 'Bear', value: 'bear'},
            {title: 'Bird', value: 'bird'},
            {title: 'Cat', value: 'cat'},
            {title: 'Cetacean', value: 'cetacean'},
            {title: 'Cow', value: 'cow'},
            {title: 'Crocodilia', value: 'crocodilia'},
            {title: 'Dog', value: 'dog'},
            {title: 'Fish', value: 'fish'},
            {title: 'Horse', value: 'horse'},
            {title: 'Insect', value: 'insect'},
            {title: 'Lion', value: 'lion'},
            {title: 'Rabbit', value: 'rabbit'},
            {title: 'rodent', value: 'rodent'},
            {title: 'Snake', value: 'snake'},
            {title: 'type', value: 'type'},
        ],
        color:[
            {title: 'HSL', value: 'hsl'},
            {title: 'Human', value: 'human'},
            {title: 'Hwb', value: 'hwb'},
            {title: 'Lab', value: 'lab'},
            {title: 'LCH', value: 'lch'},
            {title: 'RGB', value: 'rgb'},
            {title: 'Space', value: 'space'},

        ],
        commerce: [
            {title: 'Department', value: 'department'},
            {title: 'Price', value: 'price'},
            {title: 'Product', value: 'product'},
            {title: 'Product Adjective', value: 'productAdjective'},
            {title: 'Product Material', value: 'productMaterial'},
            {title: 'Product Name', value: 'productName'},
        ],
        company: [
            {title: 'BS', value: 'bs'},
            {title: 'Bs Adjective', value: 'bsAdjective'},
            {title: 'Bs Buzz', value: 'bsBuzz'},
            {title: 'Bs Noun', value: 'bsNoun'},
            {title: 'Catch Phrase', value: 'catchPhrase'},
            {title: 'Catch Phrase Adjective', value: 'catchPhraseAdjective'},
            {title: 'Catch Phrase Descriptor', value: 'catchPhraseDescriptor'},
            {title: 'Catch Phrase Noun', value: 'catchPhraseNoun'},
            {title: 'Company Suffix', value: 'companySuffix'},
            {title: 'name', value: 'name'},
            {title: 'Suffixes', value: 'suffixes'},
        ],
        database: [
            {title: 'Collation', value: 'collation'},
            {title: 'Column', value: 'column'},
            {title: 'Engine', value: 'engine'},
            {title: 'Type', value: 'type'},
        ],
        datatype: [],
        date: [
            {title: 'Between', value: 'between'},
            {title: 'Betweens', value: 'betweens'},
            {title: 'Birthdate', value: 'birthdate'},
            {title: 'Future', value: 'future'},
            {title: 'Month', value: 'month'},
            {title: 'Past', value: 'past'},
            {title: 'Recent', value: 'recent'},
            {title: 'Soon', value: 'soon'},
            {title: 'Weekday', value: 'weekday'},
        ],
        finance: [
            {title: 'Account', value: 'account'},
            {title: 'Account Name', value: 'accountName'},
            {title: 'Amount', value: 'amount'},
            {title: 'Bic', value: 'bic'},
            {title: 'Bitcoin Address', value: 'bitcoinAddress'},
            {title: 'Credit Card CVV', value: 'creditCardCVV'},
            {title: 'Credit Card CVV', value: 'creditCardCVV'},
            {title: 'Credit Card Issuer', value: 'creditCardIssuer'},
            {title: 'Credit Card Number', value: 'creditCardNumber'},
            {title: 'Currency Code', value: 'currencyCode'},
            {title: 'Currency Name', value: 'currencyName'},
            {title: 'Currency Symbol', value: 'currencySymbol'},
            {title: 'Ethereum Address', value: 'ethereumAddress'},
            {title: 'IBAN', value: 'iban'},
            {title: 'Litecoin Address', value: 'litecoinAddress'},
            {title: 'Mask', value: 'mask'},
            {title: 'Pin', value: 'pin'},
            {title: 'Routing Number', value: 'routingNumber'},
            {title: 'Transaction Description', value: 'transactionDescription'},
            {title: 'Transaction Type', value: 'transactionType'},
        ],
        git: [
            {title: 'Branch', value: 'branch'},
            {title: 'Commit Entry', value: 'commitEntry'},
            {title: 'Commit Message', value: 'commitMessage'},
            {title: 'Commit Sha', value: 'commitSha'},
            {title: 'Short Sha', value: 'shortSha'},
        ],
        hacker: [
            {title: 'Abbreviation', value: 'abbreviation'},
            {title: 'Adjective', value: 'adjective'},
            {title: 'Ing Verb', value: 'ingVerb'},
            {title: 'Noun', value: 'noun'},
            {title: 'Phrase', value: 'phrase'},
            {title: 'Verb', value: 'verb'},
        ],
        image: [
            {title: 'Abstract', value: 'abstract'},
            {title: 'Animals', value: 'animals'},
            {title: 'Avatar', value: 'avatar'},
            {title: 'Business', value: 'business'},
            {title: 'Cats', value: 'cats'},
            {title: 'City', value: 'city'},
            {title: 'Data URI', value: 'dataUri'},
            {title: 'Fashion', value: 'fashion'},
            {title: 'Food', value: 'food'},
            {title: 'Image', value: 'image'},
            {title: 'Image URL', value: 'imageUrl'},
            {title: 'Nature', value: 'nature'},
            {title: 'Nightlife', value: 'nightlife'},
            {title: 'People', value: 'people'},
            {title: 'Sports', value: 'sports'},
            {title: 'Technics', value: 'technics'},
            {title: 'Transport', value: 'transport'},
        ],
        internet: [
            {title: 'Avatar', value: 'avatar'},
            {title: 'Color', value: 'color'},
            {title: 'Domain Name', value: 'domainName'},
            {title: 'Domain Suffix', value: 'domainSuffix'},
            {title: 'Domain Word', value: 'domainWord'},
            {title: 'Email', value: 'email'},
            {title: 'Emoji', value: 'emoji'},
            {title: 'Example Email', value: 'exampleEmail'},
            {title: 'HTTP Method', value: 'httpMethod'},
            {title: 'HTTP Status Code', value: 'httpStatusCode'},
            {title: 'IP', value: 'ip'},
            {title: 'IPV4', value: 'ipv4'},
            {title: 'IPV6', value: 'ipv6'},
            {title: 'MAC', value: 'mac'},
            {title: 'Password', value: 'password'},
            {title: 'port', value: 'port'},
            {title: 'Protocol', value: 'protocol'},
            {title: 'Url', value: 'url'},
            {title: 'User Agent', value: 'userAgent'},
            {title: 'Username', value: 'username'},
        ],
        lorem:[
            {title: 'Lines', value: 'lines'},
            {title: 'Paragraph', value: 'paragraph'},
            {title: 'Paragraphs', value: 'paragraphs'},
            {title: 'Sentence', value: 'sentence'},
            {title: 'Sentences', value: 'sentences'},
            {title: 'Slug', value: 'slug'},
            {title: 'text', value: 'text'},
            {title: 'Word', value: 'word'},
            {title: 'Words', value: 'words'},
        ],
        mersenne: [
            {title: 'Rand', value: 'rand'},
            {title: 'Seed', value: 'seed'},
            {title: 'Seed Array', value: 'seedArray'},
        ],
        music: [
            {title: 'Genre', value: 'genre'},
            {title: 'Song Name', value: 'songName'},
        ],
        name: [
            {title: 'First Name', value: 'firstName'},
            {title: 'Full Name', value: 'fullName'},
            {title: 'Gender', value: 'gender'},
            {title: 'Job Area', value: 'jobArea'},
            {title: 'Job Descriptor', value: 'jobDescriptor'},
            {title: 'Job Title', value: 'jobTitle'},
            {title: 'Job Type', value: 'jobType'},
            {title: 'Last Name', value: 'lastName'},
            {title: 'Middle Name', value: 'middleName'},
            {title: 'Prefix', value: 'prefix'},
            {title: 'Sex', value: 'sex'},
            {title: 'Sex Type', value: 'sexType'},
            {title: 'Suffix', value: 'suffix'},
        ],
        phone: [
            {title: 'IMEI', value: 'imei'},
            {title: 'Number', value: 'number'},
        ],
        random: [
            {title: 'Alpha', value: 'alpha'},
            {title: 'Alpha Numeric', value: 'alphaNumeric'},
            {title: 'Locale', value: 'locale'},
            {title: 'Numeric', value: 'numeric'},
            {title: 'Word', value: 'word'},
            {title: 'Words', value: 'words'},
        ],
        science: [
            {title: 'Chemical Element', value: 'chemicalElement'},
            {title: 'Unit', value: 'unit'},
        ],
        system: [
            {title: 'Common File Ext', value: 'commonFileExt'},
            {title: 'Common File Name', value: 'commonFileName'},
            {title: 'Common File Type', value: 'commonFileType'},
            {title: 'CRON', value: 'cron'},
            {title: 'Directory Path', value: 'directoryPath'},
            {title: 'File Ext', value: 'fileExt'},
            {title: 'File Name', value: 'fileName'},
            {title: 'File Path', value: 'filePath'},
            {title: 'File Type', value: 'fileType'},
            {title: 'MIME Type', value: 'mimeType'},
            {title: 'Network Interface', value: 'networkInterface'},
            {title: 'Semver', value: 'semver'},
        ],
        vehicle: [
            {title: 'Bicycle', value: 'bicycle'},
            {title: 'Fuel', value: 'fuel'},
            {title: 'Manufacturer', value: 'manufacturer'},
            {title: 'Model', value: 'model'},
            {title: 'Type', value: 'type'},
            {title: 'Vehicle', value: 'vehicle'},
            {title: 'Vin', value: 'vin'},
            {title: 'Vrm', value: 'vrm'},
        ],
    }
const fakers = [
    {title: 'Address', value: 'address', description: `${fakerTypes.address.map((type) => type.title).join(', ')}`},
    {title: 'Animal', value: 'animal', description: `${fakerTypes.animal.map((type) => type.title).join(', ')}`},
    {title: 'Color', value: 'color', description: `${fakerTypes.color.map((type) => type.title).join(', ')}`},
    {title: 'Commerce', value: 'commerce', description: `${fakerTypes.commerce.map((type) => type.title).join(', ')}`},
    {title: 'Company', value: 'company', description: `${fakerTypes.company.map((type) => type.title).join(', ')}`},
    {title: 'Database', value: 'database', description: `${fakerTypes.database.map((type) => type.title).join(', ')}`},
    //{title: 'Data Type', value: 'datatype'},
    {title: 'Date', value: 'date', description: `${fakerTypes.date.map((type) => type.title).join(', ')}`},
    {title: 'Finance', value: 'finance', description: `${fakerTypes.finance.map((type) => type.title).join(', ')}`},
    {title: 'Git', value: 'git', description: `${fakerTypes.git.map((type) => type.title).join(', ')}`},
    {title: 'Hacker', value: 'hacker', description: `${fakerTypes.hacker.map((type) => type.title).join(', ')}`},
    {title: 'Image', value: 'image', description: `${fakerTypes.image.map((type) => type.title).join(', ')}`},
    {title: 'Internet', value: 'internet', description: `${fakerTypes.internet.map((type) => type.title).join(', ')}`},
    {title: 'Lorem', value: 'lorem', description: `${fakerTypes.lorem.map((type) => type.title).join(', ')}`},
    {title: 'Mersenne', value: 'mersenne', description: `${fakerTypes.mersenne.map((type) => type.title).join(', ')}`},
    {title: 'Music', value: 'music', description: `${fakerTypes.music.map((type) => type.title).join(', ')}`},
    {title: 'Name', value: 'name', description: `${fakerTypes.name.map((type) => type.title).join(', ')}`},
    {title: 'Phone', value: 'phone', description: `${fakerTypes.phone.map((type) => type.title).join(', ')}`},
    {title: 'Random', value: 'random', description: `${fakerTypes.random.map((type) => type.title).join(', ')}`},
    {title: 'Science', value: 'science', description: `${fakerTypes.science.map((type) => type.title).join(', ')}`},
    {title: 'System', value: 'system', description: `${fakerTypes.system.map((type) => type.title).join(', ')}`},
    {title: 'Vehicle', value: 'vehicle', description: `${fakerTypes.vehicle.map((type) => type.title).join(', ')}`},
    
]

module.exports = {
    fakers,
    fakerTypes,
}